base: 'https://mens-circle.de/'
baseVariants:
  - base: 'https://mens-circle.ddev.site/'
    condition: 'applicationContext == "Development/Local"'
  - base: 'https://mens-circle.ddev.site/'
    condition: 'applicationContext == "Production/Local"'
disableStaticFileCache: false
languages:
  - title: Deutsch
    enabled: true
    languageId: 0
    base: /
    locale: de_DE.UTF-8
    navigationTitle: Deutsch
    flag: de
rootPageId: 1
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      /: 0
      sitemap.xml: 1533906435
  EventDetail:
    type: Extbase
    extension: Sitepackage
    namespace: tx_sitepackage_eventdetail
    plugin: EventDetail
    routes:
      - routePath: '/{event_title}'
        _controller: 'Event::detail'
        _arguments:
          event_title: event
      - routePath: '/{event_title}/ical'
        _controller: 'Event::iCal'
        _arguments:
          event_title: event
    defaultController: 'Event::detail'
    aspects:
      event_title:
        type: PersistedAliasMapper
        tableName: tx_sitepackage_domain_model_event
        routeFieldName: slug
websiteTitle: 'Menâ€™s Circle Niederbayern'
